/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export declare function bunPluginRegister(): void

/**
 * Called from TypeScript's `jsBridge(fn)` to register the user's JS callback.
 *
 * Returns `External<Arc<BridgeFn>>` — an opaque value passed as `external` in
 * `build.onBeforeParse(matcher, { napiModule, symbol, external })`.
 * Bun hands this pointer back to `bun_js_bridge_dispatch` on every file.
 *
 * Uses napi-rs v3's Function builder. The JS callback is called as fn(source, path)
 * with callee_handled=false (no null error-first arg). Return type is String.
 */
export declare function createBridge(callback: (arg: [string, string]) => string): ExternalObject<BridgeFn>

/**
 * Call this after your build completes to release the TSFN reference, allowing
 * the event loop to exit. Without this, the process hangs waiting for more calls.
 *
 * Call this after your build completes if you need explicit cleanup.
 *
 * With Weak=true (set in create_bridge), the TSFN does not hold a strong event-loop
 * reference — the process can exit freely once the event loop drains. This function
 * exists for API compatibility and as a documentation anchor; it is a no-op.
 *
 * In napi v3, External parameters are received as `&External<T>` (borrowed from JS heap).
 */
export declare function releaseBridge(bridge: ExternalObject<BridgeFn>): void
